### ISSUE TITLE
Add source code verifier

### ISSUE THREAD

**Issue by ngundotra** [KunalBagaria/solana-vision#1]
This is a sick project! It would be awesome to get more adoption.

I am concerned about the possibility of someone forking this repository & hosting it under a different but related domain, and then maliciously replacing the `mint-nft` app with a transaction that steals user funds.

A possible solution to this would be a visual indicator that checks if the transaction-generating source codes matches the current release of the repo.

Thoughts? I suggest adding something like the github verified button
<img width="81" alt="Screen Shot 2022-09-15 at 9 07 47 AM" src="https://user-images.githubusercontent.com/7481857/190411727-b5d8e3b0-1492-4d9b-88c9-345b78e99b93.png">

**Comment by KunalBagaria** [comment]
sounds good to me, would love to implement something like this

**Comment by KunalBagaria** [comment]
there's an issue with this however, if someone goes as far as forking the repository, then can just override the verification badge as well
